<?php
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \EdicionesMox\Storefront\ViewModel\Navigation|null $navigationViewModel
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
/**
 * @var \Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolverInterface|null $logoSizeResolver
 */
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
$navigationViewModel = $block->getData('navigation_view_model');
$ariaLabelToggleNav = $navigationViewModel
    ? $navigationViewModel->getAriaLabelToggleNav()
    : (string) __('Toggle main navigation');
?>
<span data-action="toggle-nav" class="action nav-toggle">
    <span><?= $escaper->escapeHtml(__('Toggle Nav')) ?></span>
</span>
<a
    class="logo"
    href="<?= $escaper->escapeUrl($block->getUrl('')) ?>"
    title="<?= $escaper->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img src="<?= $escaper->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
        <?= $logoWidth ? 'width="' . $escaper->escapeHtmlAttr($logoWidth) . '"' : '' ?>
        <?= $logoHeight ? 'height="' . $escaper->escapeHtmlAttr($logoHeight) . '"' : '' ?>
    />
</a>
<script type="text/x-magento-init">
{
    ".page-header": {
        "edmoxNavigation": {
            "ariaLabel": "<?= $escaper->escapeJs($ariaLabelToggleNav) ?>"
        }
    }
}
</script>
